### ISSUE TITLE
T_Dwe_DngRuin_I_CaveSH gaps

### ISSUE THREAD

**Issue by Snailsting** [TD-Addon/TD_Addon#593]
Both `tr/i/tr_in_dwrv_shcave_00.nif` and `tr/i/tr_in_dwrv_shcavens_00.nif` have some gaps on one side of the dwarven part

![JohnGap](https://github.com/TD-Addon/TD_Addon/assets/120365872/caa2efe9-08ad-4737-b54c-126d469aec83)

**Comment by antonisauren** [comment]
[i.zip](https://github.com/TD-Addon/TD_Addon/files/14575726/i.zip)
Fixed those two verts.

**Comment by Snailsting** [comment]
The versions in the current Addon still have this issue because fixed models were overwritten with unfixed ones in https://github.com/TD-Addon/TD_Addon/commit/d0462916b7636bef9105545fefd7babd45826118
